package Utile;

public enum Functie {
    SUBLOCOTENENT, LOCOTENENT, CAPITAN, MAIOR, LOCOTENENT_COLONEL, COLONEL, GENERAL_DE_BRIGADA, GENERAL_MAIOR,
    GENERAL_LOCOTENENT, GENERAL_MARESAL, SOLDAT, FRUNTAS, CAPORAL, SERGENT, SERGENT_MAJOR, PLUTONIER, PLUTONIER_MAJOR,
    PLUTONIER_ADJUTANT, PLUTONIER_ADJUTANT_PRINCIPAL
}
